[Conf] Add service kwapi status and start only if not running

diff --git a/etc/init/kwapi b/etc/init/kwapi
--- a/etc/init/kwapi
+++ b/etc/init/kwapi
@@ -8,6 +8,7 @@
 # short-description: configure kwapi to monitor energy on sites
 # Description: energy monitoring, RRD, live visualization, long-term storage, ganglia
 ### END INIT INFO
+#set -e
 
 # Author: Laurent Pouilloux, François Rossigneux
 #
@@ -44,11 +45,16 @@ pid_element () {
     echo /var/run/$1.pid
 }
 
+# Start only if daemon is not running
 daemon_start () {
     EXEC=${1//_/-}
     log_action_msg "Starting ${EXEC,,}"
     PID=$(pid_element $1)
-    start-stop-daemon --start --make-pidfile --pidfile $PID --exec ${PREFIX}${EXEC,,} --chuid $USER --background
+    if !( status_of_proc -p $PID ${PREFIX}${EXEC,,} ${EXEC,,} > /dev/null ); then
+        start-stop-daemon --start --make-pidfile --pidfile $PID --chuid $USER --background --exec ${PREFIX}${EXEC,,}
+    else
+        log_warning_msg "${EXEC,,} is already running"
+    fi
     sleep 1
 }
 
@@ -57,6 +63,12 @@ daemon_stop () {
     log_action_msg "Stopping ${EXEC,,}"
     PID=$(pid_element $1)
     start-stop-daemon --stop --pidfile $PID
+}
+
+daemon_status () {
+    EXEC=${1//_/-}
+    PID=$(pid_element $1)
+    status_of_proc -p $PID ${PREFIX}${EXEC,,} ${EXEC,,} && return 0 || return $?
 }
 
 # Carry out specific functions when asked to by the system
@@ -81,8 +93,19 @@ case "$1" in
     $0 stop
     $0 start
   ;;
+  status)
+    # Return != 0 if one of the daemon failed
+    FAIL=0
+    for element in $kwapi_elements
+    do
+        if eval "$"$element; then
+            daemon_status $element || let "FAIL=1"
+        fi
+    done
+    exit $FAIL
+  ;;
   *)
-    echo "Usage: /etc/init.d/kwapi {start|stop|restart}"
+    echo "Usage: /etc/init.d/kwapi {start|stop|restart|status}"
     exit 1
     ;;
 esac
